"""add_patent_cache_tables

Revision ID: 6dafcfc04c9a
Revises: 4733b9f7f80a
Create Date: 2026-01-23 19:45:44.740839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dafcfc04c9a'
down_revision: Union[str, Sequence[str], None] = '4733b9f7f80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_number', sa.String(), nullable=False),
    sa.Column('invention_title', sa.Text(), nullable=False),
    sa.Column('invention_title_en', sa.Text(), nullable=True),
    sa.Column('applicant_name', sa.String(), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('open_number', sa.String(), nullable=True),
    sa.Column('open_date', sa.Date(), nullable=True),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('registration_date', sa.Date(), nullable=True),
    sa.Column('registration_status', sa.String(), nullable=True),
    sa.Column('astrt_cont', sa.Text(), nullable=True),
    sa.Column('drawing', sa.String(), nullable=True),
    sa.Column('big_drawing', sa.String(), nullable=True),
    sa.Column('kipris_doc_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patents_application_date', 'patents', ['application_date'], unique=False)
    op.create_index(op.f('ix_patents_application_number'), 'patents', ['application_number'], unique=True)
    op.create_table('patent_ipc_codes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patent_id', sa.Uuid(), nullable=False),
    sa.Column('ipc_code', sa.String(), nullable=False),
    sa.Column('ipc_code_4', sa.String(), nullable=False),
    sa.Column('ipc_code_8', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patent_id', 'ipc_code', name='uq_patent_ipc')
    )
    op.create_index('ix_patent_ipc_code_4', 'patent_ipc_codes', ['ipc_code_4'], unique=False)
    op.create_index('ix_patent_ipc_code_8', 'patent_ipc_codes', ['ipc_code_8'], unique=False)
    op.create_index(op.f('ix_patent_ipc_codes_ipc_code'), 'patent_ipc_codes', ['ipc_code'], unique=False)
    op.create_index(op.f('ix_patent_ipc_codes_ipc_code_4'), 'patent_ipc_codes', ['ipc_code_4'], unique=False)
    op.create_index(op.f('ix_patent_ipc_codes_ipc_code_8'), 'patent_ipc_codes', ['ipc_code_8'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patent_ipc_codes_ipc_code_8'), table_name='patent_ipc_codes')
    op.drop_index(op.f('ix_patent_ipc_codes_ipc_code_4'), table_name='patent_ipc_codes')
    op.drop_index(op.f('ix_patent_ipc_codes_ipc_code'), table_name='patent_ipc_codes')
    op.drop_index('ix_patent_ipc_code_8', table_name='patent_ipc_codes')
    op.drop_index('ix_patent_ipc_code_4', table_name='patent_ipc_codes')
    op.drop_table('patent_ipc_codes')
    op.drop_index(op.f('ix_patents_application_number'), table_name='patents')
    op.drop_index('ix_patents_application_date', table_name='patents')
    op.drop_table('patents')
    # ### end Alembic commands ###
